# Generated by Django 5.2 on 2025-04-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("voter", "Voter"),
                    ("candidate", "Candidate"),
                    ("election_officer", "Election Officer"),
                    ("media", "Media"),
                    ("observer", "Observer"),
                    ("party_agent", "Party Agent"),
                    ("party_rep", "Party Representative"),
                    ("other", "Other"),
                ],
                default="voter",
                max_length=40,
            ),
        ),
    ]
