# Generated by Django 5.2 on 2025-05-02 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_role"),
        (
            "stations",
            "0011_rename_polling_station_pollingstation_polling_center_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="polling_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polling_center",
                to="stations.pollingcenter",
            ),
        ),
    ]
