# Generated by Django 5.2.1 on 2026-09-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_is_phone_verified_phoneverificationchallenge_and_more"),
        ("knox", "0009_extend_authtoken_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="NativeToken",
            fields=[],
            options={
                "verbose_name": "Native sign-in",
                "verbose_name_plural": "Native sign-ins",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("knox.authtoken",),
        ),
    ]
