# Generated by Django 5.2.1 on 2025-10-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("results", "0006_pollingstationpresidentialresults_added_by"),
        ("stations", "0016_pollingcenter_location_upvotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aspirant2017",
            fields=[
                (
                    "aspirant_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="results.aspirant",
                    ),
                ),
                ("year", models.PositiveIntegerField(default=2017)),
            ],
            options={
                "verbose_name": "2017 Aspirant",
                "verbose_name_plural": "2017 Aspirants",
            },
            bases=("results.aspirant",),
        ),
        migrations.CreateModel(
            name="PresidentialResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_voters", models.PositiveIntegerField()),
                ("aspirant_votes", models.PositiveIntegerField()),
                ("total_valid_votes", models.PositiveIntegerField()),
                ("rejected_ballots", models.PositiveIntegerField()),
                (
                    "aspirant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pres_results_2017",
                        to="historical.aspirant2017",
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presidential_results",
                        to="stations.county",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presidential Results",
                "verbose_name_plural": "Presidential Results",
                "unique_together": {("county", "aspirant")},
            },
        ),
    ]
