# Generated by Django 5.2.1 on 2025-10-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historical", "0002_governorresults"),
    ]

    operations = [
        migrations.AddField(
            model_name="aspirant2017",
            name="is_running_mate",
            field=models.BooleanField(default=False),
        ),
    ]
