# Generated by Django 5.2.1 on 2025-10-28 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historical", "0003_aspirant2017_is_running_mate"),
        ("stations", "0016_pollingcenter_location_upvotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SenatorResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aspirant_votes", models.PositiveIntegerField()),
                (
                    "aspirant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sen_results_2017",
                        to="historical.aspirant2017",
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senator_results",
                        to="stations.county",
                    ),
                ),
            ],
            options={
                "verbose_name": "Senator Results",
                "verbose_name_plural": "Senator Results",
                "unique_together": {("county", "aspirant")},
            },
        ),
    ]
