# Generated by Django 5.2.1 on 2025-10-28 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historical", "0006_mpresults"),
        ("stations", "0016_pollingcenter_location_upvotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCAResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aspirant_votes", models.PositiveIntegerField()),
                (
                    "aspirant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mca_results_2017",
                        to="historical.aspirant2017",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mca_results",
                        to="stations.ward",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCA Results",
                "verbose_name_plural": "MCA Results",
                "unique_together": {("ward", "aspirant")},
            },
        ),
    ]
