# Generated by Django 5.2.1 on 2026-10-03 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("body", models.TextField()),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "access_policy",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("RESTRICTED_LISTED", "Restricted Listed"),
                            ("RESTRICTED_CONCEALED", "Restricted Concealed"),
                        ],
                        default="RESTRICTED_CONCEALED",
                        max_length=24,
                    ),
                ),
                ("safe_listing_title", models.CharField(blank=True, max_length=200)),
                ("safe_listing_summary", models.TextField(blank=True)),
                ("archived", models.BooleanField(default=False)),
                (
                    "current_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="specs.revision",
                    ),
                ),
                (
                    "readers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="readable_specifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="specs.specification",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="revision",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="specs.specification",
            ),
        ),
        migrations.AddConstraint(
            model_name="revision",
            constraint=models.UniqueConstraint(
                fields=("specification", "sequence"),
                name="specs_revision_unique_sequence",
            ),
        ),
    ]
