# Generated by Django 5.2.1 on 2026-10-03 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="specification",
            name="draft_body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="specification",
            name="draft_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="specification",
            name="draft_title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.CreateModel(
            name="AuthorGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specification_author_grant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("PUBLISHED", "Published"),
                            ("POLICY_CHANGED", "Policy Changed"),
                            ("READER_ADDED", "Reader Added"),
                            ("READER_REMOVED", "Reader Removed"),
                            ("AUTHOR_GRANTED", "Author Granted"),
                            ("AUTHOR_REVOKED", "Author Revoked"),
                        ],
                        max_length=16,
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("detail", models.CharField(blank=True, max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="specs.specification",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
