# Generated by Django 5.2.1 on 2026-10-07 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specs", "0002_authoring"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("ordered", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="specification",
            name="position",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="specification",
            name="stage",
            field=models.CharField(
                choices=[
                    ("BRAINDUMP", "Braindump"),
                    ("DRAFT", "Draft"),
                    ("ACCEPTED", "Accepted"),
                    ("LIVE", "Live"),
                ],
                default="DRAFT",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="specification",
            name="document_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specifications",
                to="specs.documentset",
            ),
        ),
    ]
