# Generated by Django 5.2 on 2025-04-19 08:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="county",
            name="multi_boundary",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
