# Generated by Django 5.2 on 2025-04-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0002_county_multi_boundary"),
    ]

    operations = [
        migrations.AddField(
            model_name="constituency",
            name="is_diaspora",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="county",
            name="is_diaspora",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ward",
            name="is_diaspora",
            field=models.BooleanField(default=False),
        ),
    ]
