# Generated by Django 5.2 on 2025-04-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0003_constituency_is_diaspora_county_is_diaspora_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="constituency",
            name="is_prisons",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="county",
            name="is_prisons",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ward",
            name="is_prisons",
            field=models.BooleanField(default=False),
        ),
    ]
