# Generated by Django 5.2 on 2025-04-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0005_pollingcenter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollingcenter",
            name="number_of_streams",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
