# Generated by Django 5.2 on 2025-04-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0006_alter_pollingcenter_number_of_streams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollingcenter",
            name="code",
            field=models.CharField(editable=False, max_length=8),
        ),
    ]
