# Generated by Django 5.2 on 2025-04-21 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0007_alter_pollingcenter_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pollingcenter",
            options={
                "verbose_name": "Polling Center",
                "verbose_name_plural": "Polling Centers",
            },
        ),
        migrations.AlterUniqueTogether(
            name="pollingcenter",
            unique_together={("code", "ward", "name")},
        ),
    ]
