# Generated by Django 5.2 on 2025-04-21 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0009_pollingstation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pollingstation",
            options={
                "verbose_name": "Polling Station",
                "verbose_name_plural": "Polling Stations",
            },
        ),
        migrations.AlterUniqueTogether(
            name="pollingstation",
            unique_together={("polling_station", "code")},
        ),
    ]
