# Generated by Django 5.2 on 2025-04-21 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0010_alter_pollingstation_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pollingstation",
            old_name="polling_station",
            new_name="polling_center",
        ),
        migrations.AlterUniqueTogether(
            name="pollingstation",
            unique_together={("polling_center", "code")},
        ),
        migrations.RemoveField(
            model_name="pollingstation",
            name="name",
        ),
    ]
