# Generated by Django 5.2.1 on 2025-05-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stations",
            "0011_rename_polling_station_pollingstation_polling_center_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pollingcenter",
            name="pin_location_error",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
