# Generated by Django 5.2.1 on 2025-05-24 05:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0012_pollingcenter_pin_location_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollingcenter",
            name="boundary",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="pollingcenter",
            name="radius",
            field=models.FloatField(default=0.05, help_text="km"),
        ),
    ]
