# Generated by Django 5.2.1 on 2025-06-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0014_pollingcenterverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollingcenterverification",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
