# Generated by Django 5.2.1 on 2025-06-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0015_pollingcenterverification_date_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollingcenter",
            name="location_upvotes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
