# Generated by Django 5.2.1 on 2026-05-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0016_pollingcenter_location_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingcenterverification',
            name='ai_model',
            field=models.CharField(blank=True, help_text="Name of the AI model used, e.g., 'claude-4.7-xhigh', 'gemini-3.5-flash'.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pollingcenterverification',
            name='ai_suggestion',
            field=models.BooleanField(default=False),
        ),
    ]
