# Generated by Django 5.2.1 on 2026-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0017_pollingcenterverification_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingcenterverification',
            name='nominatim',
            field=models.BooleanField(default=False),
        ),
    ]
