# Generated by Django 5.2.1 on 2026-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0018_pollingcenterverification_nominatim'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingcenterverification',
            name='is_outlier',
            field=models.BooleanField(default=False),
        ),
    ]
