FROM node:24-alpine

RUN npm install --global corepack@0.34.5 \
    && corepack enable

WORKDIR /app

RUN chown node:node /app

USER node

COPY --chown=node:node ui/package.json ui/pnpm-lock.yaml ui/pnpm-workspace.yaml ./

RUN mkdir -p /app/.pnpm-store

RUN --mount=type=cache,id=pnpm,target=/app/.pnpm-store,uid=1000,gid=1000 \
    pnpm install --frozen-lockfile \
    && sha256sum package.json pnpm-lock.yaml \
        > node_modules/.pnpm-dependencies.checksum

COPY --chown=node:node ui/ .

RUN pnpm run build

CMD ["pnpm", "run", "dev"]
