FROM node:24-alpine

RUN npm install --global corepack@0.34.5 \
    && corepack enable

WORKDIR /app

RUN chown node:node /app

USER node

COPY --chown=node:node ui/package.json ui/pnpm-lock.yaml ui/pnpm-workspace.yaml ./

RUN --mount=type=cache,id=pnpm,target=/home/node/.local/share/pnpm/store,uid=1000,gid=1000 \
    pnpm install --frozen-lockfile

COPY --chown=node:node ui/ .

RUN pnpm run build

CMD ["pnpm", "run", "dev"]
