FROM node:20-alpine

RUN apk update && apk add --no-cache yarn

WORKDIR /app

COPY /tailwind/package.json ./package.json

COPY /tailwind/ .

RUN yarn install --no-lockfile
# RUN yarn run build 

CMD ["sh", "-c", "NODE_OPTIONS='--max-old-space-size=2048' yarn run dev"]
