
services:

  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    volumes:
      - ./ui:/app
      - react_static_volume:/app/staticfiles
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: yarn run dev
    restart: "unless-stopped"
    tty: true

  db:
    image: postgis/postgis:14-3.3
    container_name: postgis
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: db

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
      - tailwind_static_volume:/app/staticfiles
      - react_static_volume:/app/staticfiles/ui
    
    ports:
      - "8000:8000"
    depends_on:
      - db
      - webpack #This is because we need the js bundle and manifest to be created as they are needed in initial page load
    environment:
      - DEBUG=${DEBUG}
      # - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST=${DATABASE_HOST}


  tailwind:
    build:
      context: .
      dockerfile: Dockerfile.tailwind
    depends_on:
      - webpack
    volumes:
      - ./tailwind:/app
      - tailwind_static_volume:/app/css
    working_dir: /app
    command: yarn run dev
    restart: "unless-stopped"
    tty: true



volumes:
  postgres_data:
  tailwind_static_volume:
  react_static_volume:

